channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.15
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=22,<23
  # additional packages for demos
  - jupyter-server-proxy
  - nb_conda_kernels >=2.2.3
  - notebook >=7
  - packaging
