name: 'Add a documentation preview link to the PRs description'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

on:
  pull_request_target:
    types:
      - opened
    paths:
      - 'docs/**'

permissions:
  pull-requests: write

jobs:
  docs-preview-link:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: 'mamba-gator'
          single-version: true
          single-language: true
